{
  "format_version": 2,
  "sksl": {
    "entrypoint": "beam_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec4 uColor;\nuniform float uProgress;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    float dy = abs(uv.y - 0.5) * 2.0;\n    float core = smoothstep(0.1599999964237213134765625, 0.0, dy);\n    float glow = smoothstep(1.0, 0.0, dy) * 0.550000011920928955078125;\n    float head = uProgress;\n    float along = uv.x;\n    float body = smoothstep(head, head - 0.85000002384185791015625, along);\n    float spark = smoothstep(0.0599999986588954925537109375, 0.0, abs(along - head));\n    float reveal = step(along, head + 0.0199999995529651641845703125);\n    float energy = (((core + glow) * body) * reveal) + (spark * core);\n    energy = clamp(energy, 0.0, 1.39999997615814208984375);\n    vec3 rgb = uColor.xyz + (vec3(spark) * 0.60000002384185791015625);\n    float a = clamp(energy, 0.0, 1.0);\n    fragColor = vec4(rgb * a, a);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uColor",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uProgress",
        "rows": 1,
        "type": 10
      }
    ]
  }
}