{
  "format_version": 2,
  "sksl": {
    "entrypoint": "ring_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec4 uColor;\nuniform float uProgress;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 p = (uv - vec2(0.5)) * 2.0;\n    float r = length(p);\n    float ringR = mix(0.449999988079071044921875, 0.920000016689300537109375, uProgress);\n    float d = abs(r - ringR);\n    float ring = smoothstep(0.100000001490116119384765625, 0.0, d);\n    float bloom = smoothstep(0.3400000035762786865234375, 0.0, d) * 0.4000000059604644775390625;\n    float life = sin(clamp(uProgress, 0.0, 1.0) * 3.141590118408203125);\n    float a = clamp((ring + bloom) * life, 0.0, 1.0);\n    fragColor = vec4(uColor.xyz * a, a);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uColor",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uProgress",
        "rows": 1,
        "type": 10
      }
    ]
  }
}